apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: dev-

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "development"
    target:
      kind: Deployment
      name: gitops-app

images:
  - name: govinddevopsdocker/gitops-app
    newTag: latest

